[tool.poetry]
name = "feedback-bot"
version = "0.1.0"
description = "support bot with topics"
authors = ["User <johnsena322@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.17.0"
alembic = "^1.14.0"
redis = "^5.2.1"
psycopg-binary = "^3.2.3"
babel = "^2.16.0"
cachetools = "^5.5.0"
charset-normalizer = "^3.4.1"
idna = "^3.10"
pydantic-settings = "^2.7.1"
aiohttp = "^3.11.11"
asyncpg = "^0.30.0"
fluent-runtime = "^0.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
